export const TIMELINE = [
  {
    year: "2026",
    company: "Nannynow.co.uk",
    role: "Founder and front-end lead",
    outcome: "Consumer childcare product from concept to MVP, end-to-end in Next.js.",
  },
  {
    year: "2026",
    company: "Striver.Football",
    role: "Design and front-end lead",
    outcome: "Brand-as-code site with tokenised design system and headless editorial pipeline.",
  },
  {
    year: "2025",
    company: "Liberty Blume, Liberty Global",
    role: "Senior front-end engineer",
    outcome: "12+ step lending platform supporting multi-million-euro revenue.",
  },
  {
    year: "2024",
    company: "Cheam Sports FC",
    role: "Founder, front-end and full-stack engineer",
    outcome: "Production platform for 100+ families: portal, payments, admin, automation.",
  },
  {
    year: "2022",
    company: "Estée Lauder Companies",
    role: "Senior front-end engineer, EMEA",
    outcome: "Frontend modernisation across seven luxury brands; 40% dev-time cut on pilot markets.",
  },
  {
    year: "2021",
    company: "Bristol City Council",
    role: "Senior front-end engineer",
    outcome: "GOV.UK-aligned React design system; WCAG 2.1 AA for 500,000+ residents.",
  },
  {
    year: "2021",
    company: "Squiz",
    role: "Senior front-end developer",
    outcome: "Matrix CMS component libraries; 40% reduction in client build time.",
  },
  {
    year: "2020",
    company: "Boring Money",
    role: "Senior front-end developer",
    outcome: "Built boringmoneyadvice.co.uk from the ground up on Umbraco.",
  },
  {
    year: "2017",
    company: "MomentumABM",
    role: "Lead creative front-end developer",
    outcome: "ABM delivery for global tech clients; new production methodology adopted team-wide.",
  },
  {
    year: "2017",
    company: "EE",
    role: "Senior front-end developer",
    outcome: "Apple launch campaigns and EE website modernisation.",
  },
  {
    year: "2016",
    company: "A+E Networks EMEA",
    role: "Senior front-end developer",
    outcome: "Redeveloped The HISTORY Channel and BLAZE websites.",
  },
  {
    year: "2013",
    company: "Sky",
    role: "Senior front-end developer",
    outcome: "Sky Store and Sky Go consumer features at national scale.",
  },
  {
    year: "2012",
    company: "Hogarth and Ogilvy",
    role: "Front-end developer",
    outcome: "HSBC application rebuild with Mustache, Backbone, Python, Django.",
  },
  {
    year: "2010",
    company: "Comic Relief",
    role: "Front-end developer",
    outcome: "Red Nose Day campaign features at peak traffic.",
  },
  {
    year: "2007",
    company: "Inmarsat",
    role: "Web developer",
    outcome: "Company website, emails, microsites; led the development team.",
  },
  {
    year: "2006",
    company: "TUISKI",
    role: "Lead designer and front-end",
    outcome: "TUISKI websites in a Java environment.",
  },
] as const;
